concurrency:
  group: '${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.6.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.x
      - name: Install
        run: |
          npm ci
      - name: Check type
        run: |
          npm run type-check

  linter-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.6.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.x
      - name: Install
        run: |
          npm ci
      - name: Check linter
        run: |
          npm run lint

  test:
    runs-on: ubuntu-latest
    needs:
      - type-check
      - linter-check

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.6.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.x
      - name: Install
        run: |
          npm ci
      - name: Check test
        run: |
          npm run test -- --disable-coverage --passes -c -t0
